In [1]:
# nuestras librerias a utilizar
import pandas as pd
import numpy as np


# Configuraci√≥n
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [2]:
df_wd_p1 = pd.read_csv("world-data-2023_part1.csv", index_col=0)

In [3]:
df_wd_p2 = pd.read_csv("world-data-2023_part2 (2).csv", index_col=0)

In [4]:
df_wd_p1.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [5]:
df_wd_p2.head()

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"

In [7]:
wd_2023 = df_wd_p1.merge(df_wd_p2, left_on="Country", right_on="country", how="inner", suffixes=["_l", "_r"])

In [8]:
wd_2023.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"

In [9]:
columnasborrar = ["country"]
wd_2023.drop(columns=columnasborrar, inplace=True)

In [10]:
wd_2023.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:

- No tengan espacios.
- Est√©n en min√∫scula.
- No tengan par√©ntesis, es decir, quitar "(%)", "(Km2)".
- Algunas columnas tiene "\n". Eliminalos de los nombres de las columnas.
- Algunas columnas tienen ":". Eliminalos de los nombres de las columnas.

In [33]:
wd_2023.columns.str.lower().str.replace(" ", "")

Index(['country', 'density\n(p/km2)', 'abbreviation', 'agriculturalland(%)',
       'landarea(km2)', 'armedforcessize', 'birthrate', 'callingcode',
       'capital/majorcity', 'co2-emissions', 'cpi', 'cpichange(%)',
       'currency-code', 'fertilityrate', 'forestedarea(%)', 'gasolineprice',
       'gdp', 'grossprimaryeducationenrollment(%)',
       'grosstertiaryeducationenrollment(%)', 'infantmortality', 'largestcity',
       'lifeexpectancy', 'maternalmortalityratio', 'minimumwage',
       'officiallanguage', 'outofpockethealthexpenditure',
       'physiciansperthousand', 'population',
       'population:laborforceparticipation(%)', 'taxrevenue(%)',
       'totaltaxrate', 'unemploymentrate', 'urban_population', 'coordinates'],
      dtype='object')

In [39]:
wd_2023.columns=wd_2023.columns.str.lower().str.replace(" ", "")

In [40]:
wd_2023.head()

,country,density\n(p/km2),abbreviation,agriculturalland(%),landarea(km2),armedforcessize,birthrate,callingcode,capital/majorcity,co2-emissions,cpi,cpichange(%),currency-code,fertilityrate,forestedarea(%),gasolineprice,gdp,grossprimaryeducationenrollment(%),grosstertiaryeducationenrollment(%),infantmortality,largestcity,lifeexpectancy,maternalmortalityratio,minimumwage,officiallanguage,outofpockethealthexpenditure,physiciansperthousand,population,population:laborforceparticipation(%),taxrevenue(%),totaltaxrate,unemploymentrate,urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

In [47]:
wd_2023.columns

Index(['country', 'density\n(p/km2)', 'abbreviation', 'agriculturalland(%)',
       'landarea(km2)', 'armedforcessize', 'birthrate', 'callingcode',
       'capital/majorcity', 'co2-emissions', 'cpi', 'cpichange(%)',
       'currency-code', 'fertilityrate', 'forestedarea(%)', 'gasolineprice',
       'gdp', 'grossprimaryeducationenrollment(%)',
       'grosstertiaryeducationenrollment(%)', 'infantmortality', 'largestcity',
       'lifeexpectancy', 'maternalmortalityratio', 'minimumwage',
       'officiallanguage', 'outofpockethealthexpenditure',
       'physiciansperthousand', 'population',
       'population:laborforceparticipation(%)', 'taxrevenue(%)',
       'totaltaxrate', 'unemploymentrate', 'urban_population', 'coordinates'],
      dtype='object')

In [ ]:
'''columnas = ['country', 'density\n(p/km2)', 'abbreviation', 'agriculturalland(%)',
       'landarea(km2)', 'armedforcessize', 'birthrate', 'callingcode',
       'capital/majorcity', 'co2-emissions', 'cpi', 'cpichange(%)',
       'currency-code', 'fertilityrate', 'forestedarea(%)', 'gasolineprice',
       'gdp', 'grossprimaryeducationenrollment(%)',
       'grosstertiaryeducationenrollment(%)', 'infantmortality', 'largestcity',
       'lifeexpectancy', 'maternalmortalityratio', 'minimumwage',
       'officiallanguage', 'outofpockethealthexpenditure',
       'physiciansperthousand', 'population',
       'population:laborforceparticipation(%)', 'taxrevenue(%)',
       'totaltaxrate', 'unemploymentrate', 'urban_population', 'coordinates']


df = pd.DataFrame(columns=columnas)


nuevas_columnas = []

for nombre in df.columns:

   if '(' in nombre:
  	nombre = nombre.split('(')[0]
	nombre = nombre.strip()
	nombre = nombre.lower().replace(' ', '_')
	nuevas_columnas.append(nombre)

df.columns = nuevas_columnas

print(df.columns)'''

TabError: inconsistent use of tabs and spaces in indentation (<string>, line 22)

In [64]:
wd_2023.columns = wd_2023.columns.str.replace(r'\s*\(.*?\)', '', regex=True)

In [65]:
wd_2023.columns

Index(['country', 'density', 'abbreviation', 'agriculturalland', 'landarea',
       'armedforcessize', 'birthrate', 'callingcode', 'capital/majorcity',
       'co2-emissions', 'cpi', 'cpichange', 'currency-code', 'fertilityrate',
       'forestedarea', 'gasolineprice', 'gdp',
       'grossprimaryeducationenrollment', 'grosstertiaryeducationenrollment',
       'infantmortality', 'largestcity', 'lifeexpectancy',
       'maternalmortalityratio', 'minimumwage', 'officiallanguage',
       'outofpockethealthexpenditure', 'physiciansperthousand', 'population',
       'population:laborforceparticipation', 'taxrevenue', 'totaltaxrate',
       'unemploymentrate', 'urban_population', 'coordinates'],
      dtype='object')